-- USER SQL
CREATE USER cfmis IDENTIFIED BY cfmis 
DEFAULT TABLESPACE "CFMS"
TEMPORARY TABLESPACE "TEMP";

-- ROLES
GRANT "RESOURCE" TO cfmis WITH ADMIN OPTION;
GRANT "DBA" TO cfmis WITH ADMIN OPTION;
GRANT "CONNECT" TO cfmis WITH ADMIN OPTION;

-- SYSTEM PRIVILEGES

-- QUOTAS

-- USER SQL
CREATE USER cfmisis IDENTIFIED BY cfmisis 
DEFAULT TABLESPACE "CFMS"
TEMPORARY TABLESPACE "TEMP";

-- ROLES
GRANT "RESOURCE" TO cfmisis WITH ADMIN OPTION;
GRANT "DBA" TO cfmisis WITH ADMIN OPTION;
GRANT "CONNECT" TO cfmisis WITH ADMIN OPTION;

-- SYSTEM PRIVILEGES

-- QUOTAS
exit;