CREATE SMALLFILE TABLESPACE "CFMS" DATAFILE 'D:\ORACLE\PRODUCT\10.2.0\ORADATA\SHCDB1\cfms' SIZE 2G AUTOEXTEND ON NEXT 500M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

CREATE SMALLFILE TABLESPACE "PTINDEX" DATAFILE 'D:\ORACLE\PRODUCT\10.2.0\ORADATA\SHCDB1\ptindex' SIZE 500M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;

