	Select UserID,UserName,UserFName,CNIC,DOB,IsActive From tblusers;
  
  SELECT TBLUSERS.USERID,TBLUSERS.USERID||','||TRIM(TBLUSERS.CNIC)||CHR(32)||CHR(32)||CHR(32)||DECODE(IDENTITY.ENTRY_DATE,NULL,'-',TO_CHAR(IDENTITY.ENTRY_DATE,'dd-MM-yyyy')) USERS FROM TBLUSERS,IDENTITY WHERE IDENTITY.USERID(+) = TBLUSERS.USERID ORDER BY TBLUSERS.USERID DESC;
  
  select * from tblusers where userid=1;
  select * from TBLUSERSHISTORY where userid=1;
   select * from tblusers where to_number(userid)<1000;
   
   alter table tblusers modify(USERFNAME nvarchar2(200));
   
   SELECT O.OBJECT_NAME, S.SID, S.SERIAL#, P.SPID, S.PROGRAM,S.USERNAME,
S.MACHINE,S.LOGON_TIME,SQ.SQL_FULLTEXT 
FROM V$LOCKED_OBJECT L, DBA_OBJECTS O, V$SESSION S, 
V$PROCESS P, V$SQL SQ 
WHERE L.OBJECT_ID = O.OBJECT_ID 
AND L.SESSION_ID = S.SID AND S.PADDR = P.ADDR 
AND S.SQL_ADDRESS = SQ.ADDRESS;