CREATE USER "004" IDENTIFIED BY "004" DEFAULT TABLESPACE CFMS;
GRANT CONNECT,RESOURCE TO "004";
GRANT AR_INCHARGE_IS TO "004";

INSERT INTO "CFMISIS"."IDENTITY_SECTION_STAFF" (COMP_CODE, BRANCH_CODE, STATUS, FIRTNAME, JUDICIAL_SIDE, PASSWORDS) 
VALUES ('004', '103', 'ACTIVE', 'Abdul Ghaffar', 'A', '004');
commit;
--select * from user_roles;
