--------------------------------------------------------
--  File created - Wednesday-November-25-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table STD_PERSONS_IMAGES
--------------------------------------------------------
ALTER TABLE STD_PERSONS_IMAGES ADD (PERSONS_CNIC NUMBER );
  CREATE TABLE "CFMISIS"."STD_PERSONS_IMAGES" 
   (	"PERSONS_IMAGE_ID" NUMBER, 
	"PERSONS_IMAGE" BLOB, 
	"PERSONS_IMAGE_PATH" VARCHAR2(100 BYTE), 
	"PERSONS_IMAGE_FINGER1" BLOB, 
	"PERSONS_IMAGE_FINGERNO" NUMBER, 
	"PERSONS_IMAGE_LASTUPDATED_ON" DATE DEFAULT sysdate, 
	"PERSONS_IMAGE_LASTUPDATED_BY" VARCHAR2(100 BYTE), 
	"PERSONS_IMAGE_INSERTED_ON" DATE, 
	"PERSONS_IMAGE_INSERTED_BY" VARCHAR2(20 BYTE), 
	"PERSONS_IMAGE_FINGER2" BLOB, 
	"PERSONS_IMAGE_FINGER3" BLOB, 
	"PERSONS_IMAGE_FINGER4" BLOB, 
	"PERSONS_IMAGE_FINGER5" BLOB, 
	"PERSONS_IMAGE_FINGER6" BLOB, 
	"PERSONS_IMAGE_FINGER7" BLOB, 
	"PERSONS_IMAGE_FINGER8" BLOB, 
	"PERSONS_IMAGE_FINGER9" BLOB, 
	"PERSONS_IMAGE_FINGER10" BLOB, 
	"PERSON_CNIC_IMAGE" BLOB, 
	"PERSONS_CNIC" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CFMISIS" 
 LOB ("PERSONS_IMAGE") STORE AS (
  TABLESPACE "CFMISIS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) 
 LOB ("PERSONS_IMAGE_FINGER1") STORE AS (
  TABLESPACE "CFMISIS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) 
 LOB ("PERSONS_IMAGE_FINGER2") STORE AS (
  TABLESPACE "CFMISIS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) 
 LOB ("PERSONS_IMAGE_FINGER3") STORE AS (
  TABLESPACE "CFMISIS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) 
 LOB ("PERSONS_IMAGE_FINGER4") STORE AS (
  TABLESPACE "CFMISIS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) 
 LOB ("PERSONS_IMAGE_FINGER5") STORE AS (
  TABLESPACE "CFMISIS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) 
 LOB ("PERSONS_IMAGE_FINGER6") STORE AS (
  TABLESPACE "CFMISIS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) 
 LOB ("PERSONS_IMAGE_FINGER7") STORE AS (
  TABLESPACE "CFMISIS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) 
 LOB ("PERSONS_IMAGE_FINGER8") STORE AS (
  TABLESPACE "CFMISIS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) 
 LOB ("PERSONS_IMAGE_FINGER9") STORE AS (
  TABLESPACE "CFMISIS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) 
 LOB ("PERSONS_IMAGE_FINGER10") STORE AS (
  TABLESPACE "CFMISIS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) 
 LOB ("PERSON_CNIC_IMAGE") STORE AS (
  TABLESPACE "CFMISIS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) ;
--------------------------------------------------------
--  DDL for Index PERSONS_IMAGES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CFMISIS"."PERSONS_IMAGES_PK" ON "CFMISIS"."STD_PERSONS_IMAGES" ("PERSONS_IMAGE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CFMISIS" ;
--------------------------------------------------------
--  Constraints for Table STD_PERSONS_IMAGES
--------------------------------------------------------

  ALTER TABLE "CFMISIS"."STD_PERSONS_IMAGES" ADD CONSTRAINT "PERSONS_IMAGES_PK" PRIMARY KEY ("PERSONS_IMAGE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CFMISIS"  ENABLE;
 
  ALTER TABLE "CFMISIS"."STD_PERSONS_IMAGES" MODIFY ("PERSONS_IMAGE_ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Trigger STD_PERSONS_IMAGES_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CFMISIS"."STD_PERSONS_IMAGES_TRG" 
BEFORE INSERT ON STD_PERSONS_IMAGES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.PERSONS_IMAGE_ID IS NULL THEN
      SELECT STD_PERSONS_IMAGES_SEQ.NEXTVAL INTO :NEW.PERSONS_IMAGE_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;






/
ALTER TRIGGER "CFMISIS"."STD_PERSONS_IMAGES_TRG" ENABLE;
